import type { Mechanic, Review, Reservation, Product, Message, Conversation } from "./types"

export const mockMechanics: Mechanic[] = [
  {
    id: "1",
    name: "Garage Mouride",
    email: "contact@garagemouride.sn",
    phone: "+221 77 123 45 67",
    address: "Route de Rufisque, Parcelles Assainies",
    city: "Dakar",
    latitude: 14.7645,
    longitude: -17.366,
    specialties: ["Vidange", "Freins", "Révision", "Diagnostic"],
    rating: 4.8,
    reviewCount: 127,
    experience: 15,
    description:
      "Garage familial avec plus de 15 ans d'expérience. Spécialisé dans l'entretien et la réparation de tous types de véhicules.",
    image: "/professional-mechanic-garage.jpg",
    hourlyRate: 5000,
    availability: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
  },
  {
    id: "2",
    name: "Auto Service Plateau",
    email: "info@autoserviceplateau.sn",
    phone: "+221 77 234 56 78",
    address: "Avenue Léopold Sédar Senghor",
    city: "Dakar",
    latitude: 14.6928,
    longitude: -17.4467,
    specialties: ["Climatisation", "Électricité", "Carrosserie", "Peinture"],
    rating: 4.6,
    reviewCount: 89,
    experience: 10,
    description:
      "Centre auto moderne équipé des dernières technologies. Nous prenons en charge tous vos besoins automobiles.",
    image: "/modern-auto-repair-shop.png",
    hourlyRate: 6000,
    availability: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"],
  },
  {
    id: "3",
    name: "Mécanique Express Pikine",
    email: "contact@mecaniqueexpress.sn",
    phone: "+221 77 345 67 89",
    address: "Pikine Icotaf",
    city: "Pikine",
    latitude: 14.7549,
    longitude: -17.3985,
    specialties: ["Vidange rapide", "Pneus", "Batterie", "Échappement"],
    rating: 4.9,
    reviewCount: 203,
    experience: 20,
    description:
      "Service rapide et efficace pour tous vos besoins d'entretien courant. Intervention sans rendez-vous possible.",
    image: "/express-car-service.jpg",
    hourlyRate: 4500,
    availability: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"],
  },
  {
    id: "4",
    name: "Atelier Mbacké",
    email: "atelier@mbacke.sn",
    phone: "+221 77 456 78 90",
    address: "Route de Touba",
    city: "Thiès",
    latitude: 14.7886,
    longitude: -16.926,
    specialties: ["Moteur", "Transmission", "Suspension", "Direction"],
    rating: 4.7,
    reviewCount: 156,
    experience: 18,
    description:
      "Spécialistes des réparations complexes et de la mécanique de précision. Diagnostic approfondi gratuit.",
    image: "/professional-auto-workshop.jpg",
    hourlyRate: 5500,
    availability: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi"],
  },
  {
    id: "5",
    name: "Garage Moderne Guédiawaye",
    email: "info@garagemoderne.sn",
    phone: "+221 77 567 89 01",
    address: "Guédiawaye Sam Notaire",
    city: "Guédiawaye",
    latitude: 14.7692,
    longitude: -17.4089,
    specialties: ["Véhicules électriques", "Hybrides", "Diagnostic électronique"],
    rating: 4.9,
    reviewCount: 94,
    experience: 8,
    description:
      "Spécialisé dans les véhicules modernes et électriques. Formation continue sur les nouvelles technologies.",
    image: "/modern-electric-car-service.jpg",
    hourlyRate: 7000,
    availability: ["Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"],
  },
  {
    id: "6",
    name: "Pro Mécanique Rufisque",
    email: "contact@promecanique.sn",
    phone: "+221 77 678 90 12",
    address: "Centre ville Rufisque",
    city: "Rufisque",
    latitude: 14.7167,
    longitude: -17.2667,
    specialties: ["Révision complète", "Contrôle technique", "Préparation CT"],
    rating: 4.5,
    reviewCount: 178,
    experience: 12,
    description:
      "Centre agréé pour le contrôle technique. Préparation et réparation pour garantir la conformité de votre véhicule.",
    image: "/car-inspection-center.jpg",
    hourlyRate: 5000,
    availability: ["Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi"],
  },
]

export const mockReviews: Review[] = [
  {
    id: "1",
    mechanicId: "1",
    clientName: "Sophie L.",
    rating: 5,
    comment: "Service impeccable, très professionnel. Je recommande vivement!",
    date: "2025-01-10",
    service: "Vidange",
  },
  {
    id: "2",
    mechanicId: "1",
    clientName: "Marc D.",
    rating: 4,
    comment: "Bon travail, délais respectés. Prix un peu élevé mais qualité au rendez-vous.",
    date: "2025-01-08",
    service: "Freins",
  },
  {
    id: "3",
    mechanicId: "1",
    clientName: "Julie M.",
    rating: 5,
    comment: "Excellent accueil et travail soigné. Mon garage de confiance maintenant!",
    date: "2025-01-05",
    service: "Révision",
  },
]

export const mockReservations: Reservation[] = [
  {
    id: "1",
    clientId: "client1",
    clientName: "Sophie Laurent",
    mechanicId: "1",
    mechanicName: "Garage Mouride",
    service: "Vidange moteur",
    date: "2025-01-15",
    time: "14:00",
    status: "confirmed",
    notes: "Huile synthétique préférée",
    vehicleInfo: {
      make: "Renault",
      model: "Clio",
      year: 2019,
      plate: "AB-123-CD",
    },
    estimatedDuration: 60,
    estimatedPrice: 85,
    createdAt: "2025-01-10T10:30:00Z",
  },
  {
    id: "2",
    clientId: "client1",
    clientName: "Sophie Laurent",
    mechanicId: "2",
    mechanicName: "Auto Service Plateau",
    service: "Révision complète",
    date: "2025-01-20",
    time: "10:00",
    status: "pending",
    notes: "Contrôle complet avant long trajet",
    vehicleInfo: {
      make: "Peugeot",
      model: "308",
      year: 2020,
      plate: "EF-456-GH",
    },
    estimatedDuration: 180,
    estimatedPrice: 250,
    createdAt: "2025-01-12T15:20:00Z",
  },
  {
    id: "3",
    clientId: "client1",
    clientName: "Sophie Laurent",
    mechanicId: "3",
    mechanicName: "Mécanique Express Pikine",
    service: "Changement de pneus",
    date: "2024-12-28",
    time: "09:00",
    status: "completed",
    vehicleInfo: {
      make: "Renault",
      model: "Clio",
      year: 2019,
      plate: "AB-123-CD",
    },
    estimatedDuration: 45,
    estimatedPrice: 320,
    createdAt: "2024-12-20T11:00:00Z",
  },
]

export const mockProducts: Product[] = [
  {
    id: "1",
    name: "Filtre à huile premium",
    description:
      "Filtre à huile haute performance pour tous types de véhicules. Compatible avec la plupart des moteurs essence et diesel.",
    price: 7500,
    category: "Filtres",
    brand: "Bosch",
    image: "/oil-filter-product.jpg",
    stock: 45,
    vendorId: "v1",
    vendorName: "Pièces Auto Pro",
    rating: 4.7,
    reviewCount: 89,
  },
  {
    id: "2",
    name: "Plaquettes de frein avant",
    description:
      "Plaquettes de frein céramique pour une performance optimale et une durée de vie prolongée. Faible bruit et poussière réduite.",
    price: 28000,
    category: "Freinage",
    brand: "Brembo",
    image: "/brake-pads-product.jpg",
    stock: 28,
    vendorId: "v1",
    vendorName: "Pièces Auto Pro",
    rating: 4.9,
    reviewCount: 156,
  },
  {
    id: "3",
    name: "Batterie 12V 70Ah",
    description:
      "Batterie de démarrage haute capacité avec technologie AGM. Garantie 3 ans. Idéale pour véhicules modernes avec nombreux équipements électroniques.",
    price: 55000,
    category: "Électricité",
    brand: "Varta",
    image: "/car-battery-product.jpg",
    stock: 15,
    vendorId: "v2",
    vendorName: "Électro Auto",
    rating: 4.8,
    reviewCount: 203,
  },
  {
    id: "4",
    name: "Huile moteur 5W30 5L",
    description:
      "Huile moteur synthétique haute performance. Convient aux moteurs essence et diesel récents. Norme API SN/CF.",
    price: 21000,
    category: "Lubrifiants",
    brand: "Castrol",
    image: "/engine-oil-product.jpg",
    stock: 67,
    vendorId: "v1",
    vendorName: "Pièces Auto Pro",
    rating: 4.6,
    reviewCount: 124,
  },
  {
    id: "5",
    name: "Pneu été 205/55 R16",
    description:
      "Pneu été haute performance avec excellente adhérence sur route sèche et mouillée. Faible résistance au roulement pour économie de carburant.",
    price: 48000,
    category: "Pneus",
    brand: "Michelin",
    image: "/summer-tire-product.jpg",
    stock: 32,
    vendorId: "v3",
    vendorName: "Pneus Express",
    rating: 4.9,
    reviewCount: 287,
  },
  {
    id: "6",
    name: "Balais d'essuie-glace",
    description:
      "Paire de balais d'essuie-glace universels avec adaptateurs multiples. Lame en caoutchouc naturel pour un essuyage silencieux et efficace.",
    price: 11500,
    category: "Accessoires",
    brand: "Valeo",
    image: "/wiper-blades-product.jpg",
    stock: 54,
    vendorId: "v2",
    vendorName: "Électro Auto",
    rating: 4.5,
    reviewCount: 98,
  },
  {
    id: "7",
    name: "Disques de frein avant (paire)",
    description:
      "Paire de disques de frein ventilés en fonte de haute qualité. Traitement anti-corrosion pour une durée de vie prolongée.",
    price: 54000,
    category: "Freinage",
    brand: "Brembo",
    image: "/brake-discs-product.jpg",
    stock: 19,
    vendorId: "v1",
    vendorName: "Pièces Auto Pro",
    rating: 4.8,
    reviewCount: 167,
  },
  {
    id: "8",
    name: "Ampoules LED H7",
    description:
      "Paire d'ampoules LED haute luminosité pour phares. Température de couleur 6000K blanc pur. Durée de vie 50000h.",
    price: 18000,
    category: "Électricité",
    brand: "Philips",
    image: "/led-bulbs-product.jpg",
    stock: 41,
    vendorId: "v2",
    vendorName: "Électro Auto",
    rating: 4.7,
    reviewCount: 145,
  },
]

export const mockConversations: Conversation[] = [
  {
    id: "conv1",
    clientId: "client1",
    clientName: "Sophie Laurent",
    mechanicId: "1",
    mechanicName: "Garage Mouride",
    lastMessage: "Parfait, à demain alors!",
    lastMessageTime: "2025-01-14T16:30:00Z",
    unreadCount: 0,
  },
  {
    id: "conv2",
    clientId: "client1",
    clientName: "Sophie Laurent",
    mechanicId: "2",
    mechanicName: "Auto Service Plateau",
    lastMessage: "Oui, nous avons la pièce en stock",
    lastMessageTime: "2025-01-13T10:15:00Z",
    unreadCount: 2,
  },
]

export const mockMessages: Message[] = [
  {
    id: "msg1",
    conversationId: "conv1",
    senderId: "client1",
    senderName: "Sophie Laurent",
    senderRole: "client",
    receiverId: "1",
    receiverName: "Garage Mouride",
    content: "Bonjour, je souhaiterais prendre rendez-vous pour une vidange.",
    timestamp: "2025-01-14T14:00:00Z",
    read: true,
  },
  {
    id: "msg2",
    conversationId: "conv1",
    senderId: "1",
    senderName: "Garage Mouride",
    senderRole: "mechanic",
    receiverId: "client1",
    receiverName: "Sophie Laurent",
    content: "Bonjour! Bien sûr, nous avons des disponibilités demain à 14h. Cela vous convient?",
    timestamp: "2025-01-14T14:15:00Z",
    read: true,
  },
  {
    id: "msg3",
    conversationId: "conv1",
    senderId: "client1",
    senderName: "Sophie Laurent",
    senderRole: "client",
    receiverId: "1",
    receiverName: "Garage Mouride",
    content: "Parfait, à demain alors!",
    timestamp: "2025-01-14T16:30:00Z",
    read: true,
  },
  {
    id: "msg4",
    conversationId: "conv2",
    senderId: "client1",
    senderName: "Sophie Laurent",
    senderRole: "client",
    receiverId: "2",
    receiverName: "Auto Service Plateau",
    content: "Bonjour, avez-vous des plaquettes de frein pour une Peugeot 308?",
    timestamp: "2025-01-13T09:45:00Z",
    read: true,
  },
  {
    id: "msg5",
    conversationId: "conv2",
    senderId: "2",
    senderName: "Auto Service Plateau",
    senderRole: "mechanic",
    receiverId: "client1",
    receiverName: "Sophie Laurent",
    content: "Oui, nous avons la pièce en stock",
    timestamp: "2025-01-13T10:15:00Z",
    read: false,
  },
]
